# Generated by Django 4.2 on 2023-04-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declarer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('age', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('men', 'Мужчина'), ('women', 'Женщина')], max_length=7, verbose_name='Ваш пол')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('health_status', models.TextField(blank=True, default='Практичеки здоров', help_text='Аллергоgeанамнез, хронические заболевания и т.п.', verbose_name='Состояние здоровья')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Список заявителей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название службы')),
                ('cod', models.IntegerField(verbose_name='Код службы')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Экстренная служба',
                'verbose_name_plural': 'Список экс. служб',
                'ordering': ['cod'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Время обращения')),
                ('number', models.IntegerField(blank=True, db_index=True, unique=True, verbose_name='Номер обращения')),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Завершено', 'Завершено')], default='В работе', max_length=10, verbose_name='Статус')),
                ('casualties', models.IntegerField(verbose_name='Количество пострадавших')),
                ('dont_call', models.BooleanField(blank=True, null=True, verbose_name='Не звонить')),
                ('declarer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='core.declarer', verbose_name='Заявитель')),
                ('services', models.ManyToManyField(blank=True, related_name='appeals', to='core.service', verbose_name='Службы')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Список обращений',
                'ordering': ['created', 'number'],
            },
        ),
    ]
